DROP DATABASE IF EXISTS TRUONGHOC; 
CREATE DATABASE TRUONGHOC;
USE TRUONGHOC;
SET NAMES utf8;

DROP TABLE IF EXISTS lt;
CREATE TABLE lt(
	ma_lt CHAR(6) NOT NULL, 
    ten_lt VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY(ma_lt)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS lh;
CREATE TABLE lh(
	ma_lh CHAR(5) NOT NULL,
    ten_lh VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY(ma_lh)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS pgd;
CREATE TABLE pgd(
	ma_pgd CHAR(3) NOT NULL,
    ten_pgd VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY(ma_pgd)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS cap;
CREATE TABLE cap(
	ma_cap CHAR(2) NOT NULL,
    ten_cap VARCHAR(50) NOT NULL,
    PRIMARY KEY(ma_cap)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS ds_truong;
CREATE TABLE ds_truong(
	ma_truong VARCHAR(20) NOT NULL,
    ten_truong VARCHAR(100) NOT NULL,
    dia_chi VARCHAR(255) DEFAULT NULL,
    loai_hinh CHAR(5) NOT NULL,
    loai_truong CHAR(6) NOT NULL,
    phong_gd CHAR(3) NOT NULL,
    cap_dt CHAR(2) NOT NULL,
    PRIMARY KEY(ma_truong, cap_dt),
    CONSTRAINT FOREIGN KEY(loai_hinh) REFERENCES lh(ma_lh),
    CONSTRAINT FOREIGN KEY(loai_truong) REFERENCES lt(ma_lt),
    CONSTRAINT FOREIGN KEY(phong_gd) REFERENCES pgd(ma_pgd),
    CONSTRAINT FOREIGN KEY(cap_dt) REFERENCES cap(ma_cap)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

